calebasse/dossiers/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('calebasse.dossiers.views',
        url(r'^$', 'patientrecord_home'),
        url(r'^quotations$', 'patientrecord_quotations'),
        url(r'^waiting-queue$', 'patientrecord_waiting_queue'),
        url(r'^new$', 'new_patient_record'),
        url(r'^(?P<pk>\d+)/view$', 'patient_record'),
        url(r'^(?P<pk>\d+)/print$', 'patient_record_print', name='patientrecord_print'),
        url(r'^(?P<pk>\d+)/tab1$', 'tab1_general'),
        url(r'^(?P<pk>\d+)/tab2$', 'tab2_fiche_adm'),
        url(r'^(?P<pk>\d+)/tab3$', 'tab3_addresses'),
        url(r'^(?P<pk>\d+)/tab4$', 'tab4_notifs'),
        url(r'^(?P<pk>\d+)/tab5$', 'tab5_old_acts'),
        url(r'^(?P<pk>\d+)/tab6$', 'tab6_next_rdv'),
        url(r'^(?P<pk>\d+)/tab7$', 'tab7_socialisation'),
        url(r'^(?P<pk>\d+)/tab8$', 'tab8_medical'),
        url(r'^(?P<pk>\d+)/delete$', 'patientrecord_delete'),
        url(r'^(?P<pk>\d+)/update/paper_id$', 'update_paper_id'),
        url(r'^(?P<patientrecord_id>\d+)/update-state$', 'state_form'),
        url(r'^(?P<patientrecord_id>\d+)/address/new$', 'new_patient_address'),
        url(r'^(?P<patientrecord_id>\d+)/address/(?P<pk>\d+)/update$', 'update_patient_address'),
        url(r'^(?P<patientrecord_id>\d+)/address/(?P<pk>\d+)/del$', 'delete_patient_address'),
        url(r'^(?P<patientrecord_id>\d+)/contact/new$', 'new_patient_contact'),
        url(r'^(?P<patientrecord_id>\d+)/contact/(?P<pk>\d+)/update$', 'update_patient_contact'),
        url(r'^(?P<patientrecord_id>\d+)/contact/(?P<pk>\d+)/del$', 'delete_patient_contact'),
        url(r'^(?P<patientrecord_id>\d+)/healthcare_treatment/new$', 'new_healthcare_treatment'),
        url(r'^(?P<patientrecord_id>\d+)/healthcare_treatment/(?P<pk>\d+)/update$', 'update_healthcare_treatment'),
        url(r'^(?P<patientrecord_id>\d+)/healthcare_treatment/(?P<pk>\d+)/del$', 'delete_healthcare_treatment'),
        url(r'^(?P<patientrecord_id>\d+)/healthcare_diagnostic/new$', 'new_healthcare_diagnostic'),
        url(r'^(?P<patientrecord_id>\d+)/healthcare_diagnostic/(?P<pk>\d+)/update$', 'update_healthcare_diagnostic'),
        url(r'^(?P<patientrecord_id>\d+)/healthcare_diagnostic/(?P<pk>\d+)/del$', 'delete_healthcare_diagnostic'),
        url(r'^(?P<patientrecord_id>\d+)/healthcare_notification/new$', 'new_healthcare_notification'),
        url(r'^(?P<patientrecord_id>\d+)/healthcare_notification/(?P<pk>\d+)/update$', 'update_healthcare_notification'),
        url(r'^(?P<patientrecord_id>\d+)/healthcare_notification/(?P<pk>\d+)/del$', 'delete_healthcare_notification'),
        url(r'^(?P<patientrecord_id>\d+)/socialisation/new$', 'new_socialisation_duration'),
        url(r'^(?P<patientrecord_id>\d+)/socialisation/(?P<pk>\d+)/update$', 'update_socialisation_duration'),
        url(r'^(?P<patientrecord_id>\d+)/socialisation/(?P<pk>\d+)/del$', 'delete_socialisation_duration'),
        url(r'^(?P<patientrecord_id>\d+)/state/(?P<pk>\d+)/update$', 'update_patient_state'),
        url(r'^(?P<patientrecord_id>\d+)/state/(?P<pk>\d+)/del$', 'delete_patient_state'),
        url(r'^(?P<patientrecord_id>\d+)/mdph_request/new$', 'new_mdph_request'),
        url(r'^(?P<patientrecord_id>\d+)/mdph_request/(?P<pk>\d+)/update$', 'update_mdph_request'),
        url(r'^(?P<patientrecord_id>\d+)/mdph_request/(?P<pk>\d+)/del$', 'delete_mdph_request'),
        url(r'^(?P<patientrecord_id>\d+)/mdph_response/new$', 'new_mdph_response'),
        url(r'^(?P<patientrecord_id>\d+)/mdph_response/(?P<pk>\d+)/update$', 'update_mdph_response'),
        url(r'^(?P<patientrecord_id>\d+)/mdph_response/(?P<pk>\d+)/del$', 'delete_mdph_response'),
        url(r'^(?P<patientrecord_id>\d+)/generate$', 'generate_rtf_form'),
        url(r'^(?P<patientrecord_id>\d+)/create-directory$', 'create_directory', name="create_directory"),
        url(r'^(?P<patientrecord_id>\d+)/prescription-transport$', 'prescription_transport'),
        url(r'^(?P<patientrecord_id>\d+)/protection/new$', 'new_protection'),
        url(r'^(?P<patientrecord_id>\d+)/protection/(?P<pk>\d+)/update$', 'update_protection'),
        url(r'^(?P<patientrecord_id>\d+)/protection/(?P<pk>\d+)/del$', 'delete_protection'),)

calebasse/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from urls_utils import decorated_includes

from calebasse.api import (act_ressource, event_resource,
        eventwithact_resource, patientrecord_resource,
        patientaddress_ressource)
from tastypie.api import Api

admin.autodiscover()

v1_api = Api(api_name="v1")
v1_api.register(act_ressource)
v1_api.register(event_resource)
v1_api.register(eventwithact_resource)
v1_api.register(patientaddress_ressource)
v1_api.register(patientrecord_resource)

service_patterns = patterns('',
    url(r'^$', 'calebasse.views.homepage', name='homepage'),
    url(r'^agenda/', include('calebasse.agenda.urls')),
    url(r'^dossiers/', include('calebasse.dossiers.urls')),
    url(r'^actes/', include('calebasse.actes.urls')),
    url(r'^facturation/', include('calebasse.facturation.urls')),
    url(r'^personnes/', include('calebasse.personnes.urls')),
    url(r'^ressources/', include('calebasse.ressources.urls')),
    url(r'^statistics/', include('calebasse.statistics.urls')),
    url(r'^select2/', include('django_select2.urls')),
)

urlpatterns = patterns('',
    # Examples:
    # url(r'^calebasse/', include('aps42.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^$', 'calebasse.views.redirect_to_homepage'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout_then_login'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^api/',
        decorated_includes(login_required, include(v1_api.urls))),
    url(r'^(?P<service>[a-z-]+)/', decorated_includes(login_required,
        include(service_patterns))),
    url(r'^lookups/', include('ajax_select.urls')),
)

from django.conf import settings
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

calebasse/dossiers/models.py
# -*- coding: utf-8 -*-

import logging
import os

from datetime import datetime, date
from dateutil.relativedelta import relativedelta
from cPickle import loads, dumps

from django.conf import settings
from django.db import models
from django.db.models import Min, Max, Q
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

from calebasse.choices import TYPE_OF_CONTRACT_CHOICES, DEFICIENCY_CHOICES
from calebasse.models import PhoneNumberField, ZipCodeField
from calebasse.personnes.models import People
from calebasse.ressources.models import (ServiceLinkedAbstractModel,
        NamedAbstractModel)
from calebasse.actes.models import Act

from ..middleware.request import get_request
from ..utils import get_service_setting

DEFAULT_ACT_NUMBER_DIAGNOSTIC = 6
DEFAULT_ACT_NUMBER_TREATMENT = 30
DEFAULT_ACT_NUMBER_PROLONGATION = 10
VALIDITY_PERIOD_TREATMENT_HEALTHCARE_DAYS = 0
VALIDITY_PERIOD_TREATMENT_HEALTHCARE_MONTHS = 0
VALIDITY_PERIOD_TREATMENT_HEALTHCARE_YEARS = 1

logger = logging.getLogger('calebasse.dossiers')


class TransportPrescriptionLog(models.Model):
    patient = models.ForeignKey('dossiers.PatientRecord',
        verbose_name=u'Dossier patient')
    created = models.DateTimeField(u'Création', auto_now_add=True)
    choices = models.CharField(max_length = 4096, null=True, blank=True)

    def get_choices(self):
        if not self.choices:
            return dict()
        return loads(str(self.choices), protocol = 1)

    def set_choices(self, choices=None):
        if choices and isinstance(choices, dict):
            self.choices = dumps(choices, protocol = 1)


class HealthCare(models.Model):

    class Meta:
        app_label = 'dossiers'

    start_date = models.DateField(verbose_name=u"Date de début")
    request_date = models.DateField(verbose_name=u"Date de demande",
        blank=True, null=True)
    agree_date = models.DateField(verbose_name=u"Date d'accord",
        blank=True, null=True)
    insist_date = models.DateField(verbose_name=u"Date de relance",
        blank=True, null=True)
    patient = models.ForeignKey('dossiers.PatientRecord',
        verbose_name=u'Dossier patient')
    created = models.DateTimeField(u'Création', auto_now_add=True)
    author = \
        models.ForeignKey(User,
        verbose_name=u'Auteur', blank=True, null=True)
    comment = models.TextField(max_length=3000, blank=True, null=True, verbose_name=u"Commentaire")

    def get_nb_acts_cared(self):
        return len(self.act_set.all())


class CmppHealthCareDiagnostic(HealthCare):

    class Meta:
        app_label = 'dossiers'

    act_number = models.IntegerField(default=DEFAULT_ACT_NUMBER_DIAGNOSTIC, verbose_name=u"Nombre d'actes couverts")
    end_date = models.DateField(verbose_name=u"Date de fin",
        blank=True, null=True)

    def get_act_number(self):
        return self.act_number

    def set_act_number(self, value):
        if value < self.get_nb_acts_cared():
            raise Exception("La valeur doit être supérieur au "
                "nombre d'actes déjà pris en charge")
        self.act_number = value
        self.save()

    def save(self, **kwargs):
        self.start_date = \
            datetime(self.start_date.year, self.start_date.month,
                self.start_date.day)
        super(CmppHealthCareDiagnostic, self).save(**kwargs)


class CmppHealthCareTreatment(HealthCare):

    class Meta:
        app_label = 'dossiers'

    act_number = models.IntegerField(default=DEFAULT_ACT_NUMBER_TREATMENT,
            verbose_name=u"Nombre d'actes couverts")
    end_date = models.DateField(verbose_name=u"Date de fin",
        blank=True, null=True)
    prolongation = models.IntegerField(default=0,
            verbose_name=u'Prolongation')
    prolongation_date = models.DateField(verbose_name=u"Date de prolongation",
        blank=True, null=True)

    def get_act_number(self):
        if self.is_extended():
            return self.act_number + self.prolongation
        return self.act_number

    def set_act_number(self, value):
        if value < self.get_nb_acts_cared():
            raise Exception("La valeur doit être supérieur au "
                "nombre d'actes déjà pris en charge")
        self.act_number = value
        self.save()

    def is_extended(self):
        if self.prolongation > 0:
            return True
        return False

    def add_prolongation(self, value=None):
        if not value:
            value = DEFAULT_ACT_NUMBER_PROLONGATION
        if self.is_extended():
            raise Exception(u'Prise en charge déja prolongée')
        self.prolongation = value
        self.save()

    def del_prolongation(self):
        pass

    def save(self, **kwargs):
        self.start_date = \
            datetime(self.start_date.year, self.start_date.month,
                self.start_date.day)
        if not self.end_date:
            self.end_date = self.start_date + \
                relativedelta(years=VALIDITY_PERIOD_TREATMENT_HEALTHCARE_YEARS) + \
                relativedelta(months=VALIDITY_PERIOD_TREATMENT_HEALTHCARE_MONTHS) + \
                relativedelta(days=VALIDITY_PERIOD_TREATMENT_HEALTHCARE_DAYS-1)
        super(CmppHealthCareTreatment, self).save(**kwargs)


class SessadHealthCareNotification(HealthCare):

    class Meta:
        app_label = 'dossiers'

    end_date = models.DateField(verbose_name=u"Date de fin",
        blank=True, null=True)

    def save(self, **kwargs):
        self.start_date = \
            datetime(self.start_date.year, self.start_date.month,
                self.start_date.day)
        if self.end_date:
            self.end_date = \
                datetime(self.end_date.year, self.end_date.month,
                    self.end_date.day)
        super(SessadHealthCareNotification, self).save(**kwargs)

class ProtectionStatus(NamedAbstractModel):

    class Meta:
        app_label = 'dossiers'
        verbose_name = u"Statut d'une mesure de protection"
        verbose_name_plural = u"Statuts d'une mesure de protection"

class ProtectionState(models.Model):

    class Meta:
        app_label = 'dossiers'
        verbose_name = u'Mesure de protection du dossier patient'
        verbose_name_plural = u'Mesure de protections du dossier patient'
        ordering = ['-start_date']

    patient = models.ForeignKey('dossiers.PatientRecord',
        verbose_name=u'Dossier patient')
    status = models.ForeignKey('dossiers.ProtectionStatus', verbose_name=u'Statut de protection')
    created = models.DateTimeField(u'Création', auto_now_add=True)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField(blank=True, null=True)
    comment = models.TextField(max_length=3000, blank=True, null=True)

    def __unicode__(self):
        return self.status.name + ' ' + str(self.start_date)

class Status(NamedAbstractModel):

    class Meta:
        app_label = 'dossiers'
        verbose_name = u"Statut d'un état"
        verbose_name_plural = u"Statuts d'un état"

    type = models.CharField(max_length=80)
    services = models.ManyToManyField('ressources.Service')


class FileState(models.Model):

    class Meta:
        app_label = 'dossiers'
        verbose_name = u'Etat du dossier patient'
        verbose_name_plural = u'Etats du dossier patient'

    patient = models.ForeignKey('dossiers.PatientRecord',
        verbose_name=u'Dossier patient')
    status = models.ForeignKey('dossiers.Status', verbose_name=u'Statut')
    created = models.DateTimeField(u'Création', auto_now_add=True)
    date_selected = models.DateTimeField()
    author = \
        models.ForeignKey(User,
        verbose_name=u'Auteur')
    comment = models.TextField(max_length=3000, blank=True, null=True)
    previous_state = models.ForeignKey('FileState',
            on_delete=models.SET_NULL,
            verbose_name=u'Etat précédent',
            blank=True, null=True)

    def get_next_state(self):
        try:
            return FileState.objects.get(previous_state=self)
        except:
            return None

    def save(self, **kwargs):
        self.date_selected = \
                datetime(self.date_selected.year,
                        self.date_selected.month, self.date_selected.day)
        super(FileState, self).save(**kwargs)

    def __unicode__(self):
        return self.status.name + ' ' + str(self.date_selected)

    def delete(self, *args, **kwargs):
        next_state = self.get_next_state()
        if next_state and self.previous_state:
            next_state.previous_state = self.previous_state
            next_state.save()
        if self.patient.last_state == self:
            self.patient.last_state = self.previous_state
            self.patient.save()
        obj_id = self.id
        super(FileState, self).delete(*args, **kwargs)

class PatientAddress(models.Model):

    display_name = models.CharField(max_length=276,
            verbose_name=u'Adresse complète', editable=False)
    phone = PhoneNumberField(verbose_name=u"Téléphone", blank=True, null=True)
    fax = PhoneNumberField(verbose_name=u"Fax", blank=True, null=True)
    place_of_life = models.BooleanField(verbose_name=u"Lieu de vie")
    number = models.CharField(max_length=12,
            verbose_name=u"Numéro", blank=True, null=True)
    recipient = models.CharField(max_length=100,
            verbose_name=u"Destinataire", blank=True, null=True)
    street = models.CharField(max_length=100,
            verbose_name=u"Rue", blank=True, null=True)
    address_complement = models.CharField(max_length=100,
            blank=True, null=True,
            verbose_name=u"Complément d'adresse")
    zip_code = ZipCodeField(verbose_name=u"Code postal", blank=True, null=True)
    city = models.CharField(max_length=60,
            verbose_name=u"Ville", blank=True, null=True)
    comment = models.TextField(verbose_name=u"Commentaire",
            null=True, blank=True)

    def __unicode__(self):

calebasse/dossiers/templates/dossiers/generic_form.html
{% load widget_tweaks %}

<form action="{{ request.get_full_path }}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
</form>

calebasse/dossiers/templates/dossiers/patientpctrait_new.html
{% load widget_tweaks %}

<form action="{{ request.get_full_path }}" method="post">
  {% csrf_token %}
   <p>
   <label for="id_start_date">{{ form.start_date.label_tag }}</label>
   {{ form.start_date.errors }}
   <input id="id_start_date" class="date" name="start_date" value="{% now "d/m/Y" %}"/>
   </p>
   <p>
   <label for="id_act_number">{{ form.act_number.label_tag }}</label>
   {{ form.act_number.errors }}
   <input id="id_act_number" name="act_number" value="{{ form.act_number.value }}"/>
   </p>
   <p>
    <label for="id_comment">Commentaire :</label>
    <textarea id="id_comment" style="width: 90%;" name="comment"></textarea>
   </p>
 </form>

calebasse/dossiers/templates/dossiers/patientrecord_confirm_delete.html
{% load widget_tweaks %}

{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<form action="{{ request.get_full_path }}" method="post">{% csrf_token %}
  <p>Êtes-vous sûr de vouloir supprimer le dossier de {{ object.first_name }} <span class="lastname">{{ object.last_name }}</span> ?</p>
</form>

calebasse/dossiers/templates/dossiers/patientrecord_print_coordinators.html
<li><label>Coordinateurs :</label>
  {% if object.coordinators.all %}
  <ul>
    {% for coordinator in object.coordinators.all %}
    <li>{{ coordinator.first_name }} <span class="lastname">{{ coordinator.last_name }}</span></li>
    {% endfor %}
  </ul>
  {% else %}Aucun{% endif %}
</li>

calebasse/dossiers/templates/dossiers/patientrecord_tab.html
{% block print-button %}
<button class="icon-print right print">Imprimer</button>
{% endblock %}
{% block content %}
{% endblock %}
<br style="clear:both"/>
<script type="text/javascript">
    init_datepickers();
    $('button.print').on('click', function(event) {
        {% block print-actions %}{% endblock %}
        print_cleanup();
        window.print();
    });
</script>

calebasse/dossiers/templates/dossiers/patientrecord_tab1_general.html
{% extends 'dossiers/patientrecord_tab.html' %}
{% block content %}
<form method="post" action="tab1"  id="general-form" class="patientrecordform">{% csrf_token %}
<div class="left">
  <ul>
    <li>
    <label>N° dossier papier :</label> {{ object.paper_id|default_if_none:"Non renseigné" }}
    <button id="update-paper-id-btn" type='button' class="icon-edit" title="Modifier"></button>
    </li>
    <li><label>N° dossier informatique :</label> <span class="lightgray">{{ object.id }}</span></li>
    <li><label>Nom :</label> <span class="lastname">{{ object.last_name }}</span></li>
    <li><label>Prénom :</label> {{ object.first_name }}</li>
    <li><label>Genre :</label> {{ object.get_gender_display|default_if_none:"Non renseigné" }}</li>
    <li><label>Date de naissance :</label> {% if object.birthdate %}{{ object.birthdate|date:"d/m/Y" }} ({{ object.age }}){% else %}Non renseignée{% endif %}</li>
    <li>
      {% if nb_place_of_lifes == 1 %}
      <label>Lieux de vie :</label>
      {% elif nb_place_of_lifes > 1 %}
      <label class="highlight">{{ nb_place_of_lifes }} lieux de vie :</label>
      {% else %}
      <label class="highlight">Aucun lieu de vie n'est indiqué.</label>
      {% endif %}
      {% if object.addresses_contacts_comment %}<p><strong>{{ object.addresses_contacts_comment }}</strong></p>{% endif %}
        {% if object.addresses.all %}
        <ul>
          {% for address in object.addresses.all %}
          {% if address.place_of_life %}<li>✔ {{ address.display_name }}</li>{% endif %}
          {% endfor %}
        </ul>
        {% endif %}
    </li>
    <li><label>Date de contact :</label> {{ initial_state.date_selected|date:"d/m/Y" }}</li>
    <li><label>Date de création :</label> {{ object.created|date:"d/m/Y" }}</li>
    <li><label>Lieu de socialisation :</label> {{ object.school|default_if_none:"Non renseigné" }}</li>
    <li><label>Coordinateurs :</label>
        {% if object.coordinators.all %}
        <ul>
          {% for coordinator in object.coordinators.all %}
          <li>{{ coordinator.first_name }} <span class="lastname">{{ coordinator.last_name }}</span></li>
          {% endfor %}
        </ul>
        {% else %}Aucun{% endif %}
    </li>
      <li><label>Commentaire </label> <button class="save enable-on-change btn-maj">✔</button><br/>
      {{ form.comment }}
      </li>
    </ul>
  </div>
  <div class="right">
    <ul>
      <li><label>Dernier acte :</label>
      {% if last_rdv %}
      {% if last_rdv.is_absent %}<span style="font-weight: bold;">{% endif %}
        {{ last_rdv.start_datetime|date:"d/m/Y" }} -
        {% for participant in last_rdv.participants %}
        <span class="lastname">{{ participant.last_name }}</span> -
        {% endfor %}
        {{ last_rdv.act_type }}
        {% else %}
        Aucun
        {% endif %}
        {% if last_rdv.is_absent %} ({{ last_rdv.act_state }})</span>{% endif %}
      </li>
      <li><label>Prochain rendez-vous :</label>
      {% if next_rdv %}
      {% if next_rdv.is_absent %}<span style="font-weight: bold;">{% endif %}
        {{ next_rdv.start_datetime|date:"d/m/Y" }} -
        {% for participant in next_rdv.participants.all %}
        <span class="lastname">{{ participant.last_name }}</span> -
        {% endfor %}
        {{ next_rdv.act_type }}
        {% else %}
        Aucun
        {% endif %}
        {% if next_rdv.is_absent %} ({{ next_rdv.act.get_state }})</span>{% endif %}
      </li>
    </ul>
    <div class="etat">
      {% if future_state %}
      <h4>État à venir du dossier :  {{ current_state.status.name.lower }}</h4>
      <p>à partir du : {{ current_state.date_selected|date:"d/m/Y" }}</p>
      {% else %}
      <h4>État courant du dossier :  {{ current_state.status.name.lower }}</h4>
      <p>depuis le : {{ current_state.date_selected|date:"d/m/Y" }}</p>
      {% endif %}
      {% if current_state.comment %}<p><label>Commentaire :</label> {{ current_state.comment }}</p>{% endif %}
      {% for state in status %}
      <button type="button" id="{{ state.0 }}">{{ state.1 }}</button>
      {% endfor %}
      <button type="button" id="patientrecord-history">Historique</button>
      <hr/>
      <p id="confidential-msg" style="display: none; font-size: 10px;">Confidentialité mise à jour</p>
      {{ form.confidential.label_tag }} : <span class="autosubmit">{{ form.confidential }}</span>
      <p id="pause-msg" style="display: none; font-size: 10px;">Pause facturation mise à jour</p>
      {{ form.pause.label_tag }} : <span class="autosubmit">{{ form.pause }}</span>
      <br/>
      <span class="js-expandable">
      <label class="js-click-to-expand">Commentaire de la pause facturation {% if object.pause_comment %}<span title="Un commentaire existe" class="icon-comment" style="display: inline"></span>{% endif %}</label>
      <span class="js-to-expand">
        <button class="save enable-on-change btn-maj">✔</button><br/>
        {{ form.pause_comment }}
      </span>
    </div>
  </form>

    {% if object.service.name == "CMPP" %}
    <div class="notifs">
    <h4>Information sur la prise en charge</h4>
    <ul>
    <li><span{% if hc_status.1 %} class="highlight"{% endif %}>{{ hc_status.0 }}</span></li>
    {% if object.pause %}<li><span class="highlight">Le dossier est en pause facturation.</span></li>{% endif %}
    {% if missing_policy %}<li><span class="highlight">Informations d'assuré social manquantes.</span></li>{% endif %}
    {% if missing_birthdate %}<li><span class="highlight">Date de naissance manquante.</span></li>{% endif %}
    {% if object.policyholder.ame %}<li><span class="highlight">Le contact assuré est AME.</span></li>{% endif %}
    </div>
    {% endif %}


    <form method="post" action="{% url "create_directory" service object.id %}" id="create-directory-form">{% csrf_token %}
      <button>Créer répertoire patient</button>
    </form>
</div>
{% endblock %}

calebasse/dossiers/templates/dossiers/quotations_print.html
<table class="main print-only">
  {% include "dossiers/quotations_patients_table_content.html" %}
</table>

calebasse/dossiers/templates/dossiers/state.html
{% load widget_tweaks %}

<form action="{{ request.get_full_path }}" method="post">
  {% csrf_token %}
   <p class="message"/>
   <p>
   <label for="id_date">Date :</label>
   {{ form.date.errors }}
   <input id="id_date" class="date" name="date" value="{% now "d/m/Y" %}"/>
   </p>
   <p>
    <label for="id_comment">Commentaire :</label>
    <textarea id="id_comment" style="width: 90%;" name="comment"></textarea>
   </p>
 </form>

calebasse/dossiers/templates/dossiers/state_change.html
<div id="xxx-dlg">
    Etes-vous sûr de vouloir changer l'état du dossier ?
</div>