calebasse/statistics/urls.py
from django.conf.urls import patterns, include, url

from views import StatisticsHomepageView, StatisticsFormView, StatisticsDetailView

urlpatterns = patterns('',
    url(r'^$', StatisticsHomepageView.as_view()),
    url(r'^detail/(?P<name>\w{1,50})/$', view=StatisticsDetailView.as_view()),
    url(r'^form/(?P<name>\w{1,50})/$', view=StatisticsFormView.as_view()),
)

calebasse/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from urls_utils import decorated_includes

from calebasse.api import (act_ressource, event_resource,
        eventwithact_resource, patientrecord_resource,
        patientaddress_ressource)
from tastypie.api import Api

admin.autodiscover()

v1_api = Api(api_name="v1")
v1_api.register(act_ressource)
v1_api.register(event_resource)
v1_api.register(eventwithact_resource)
v1_api.register(patientaddress_ressource)
v1_api.register(patientrecord_resource)

service_patterns = patterns('',
    url(r'^$', 'calebasse.views.homepage', name='homepage'),
    url(r'^agenda/', include('calebasse.agenda.urls')),
    url(r'^dossiers/', include('calebasse.dossiers.urls')),
    url(r'^actes/', include('calebasse.actes.urls')),
    url(r'^facturation/', include('calebasse.facturation.urls')),
    url(r'^personnes/', include('calebasse.personnes.urls')),
    url(r'^ressources/', include('calebasse.ressources.urls')),
    url(r'^statistics/', include('calebasse.statistics.urls')),
    url(r'^select2/', include('django_select2.urls')),
)

urlpatterns = patterns('',
    # Examples:
    # url(r'^calebasse/', include('aps42.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^$', 'calebasse.views.redirect_to_homepage'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout_then_login'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^api/',
        decorated_includes(login_required, include(v1_api.urls))),
    url(r'^(?P<service>[a-z-]+)/', decorated_includes(login_required,
        include(service_patterns))),
    url(r'^lookups/', include('ajax_select.urls')),
)

from django.conf import settings
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

calebasse/statistics/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import Form
from ajax_select.fields import AutoCompleteSelectMultipleField

class BaseForm(Form):
    display_or_export = forms.BooleanField(label=u'Exporter dans un fichier', required=False, localize=True)

class OneDateForm(BaseForm):
    start_date = forms.DateField(label=u'Date', required=False, localize=True)

class TwoDatesForm(BaseForm):
    start_date = forms.DateField(label=u'Date de début', required=False, localize=True)
    end_date = forms.DateField(label=u'Date de fin', required=False, localize=True)

class AnnualActivityForm(BaseForm):
    start_date = forms.DateField(label=u"Date de l'année souhaitée", required=False, localize=True)
    participants = AutoCompleteSelectMultipleField('all-worker-or-group', required=False)

class PatientsTwoDatesForm(TwoDatesForm):
    patients = AutoCompleteSelectMultipleField('patientrecord', required=False)

class ParticipantsPatientsTwoDatesForm(PatientsTwoDatesForm):
    participants = AutoCompleteSelectMultipleField('all-worker-or-group', required=False)

class PatientsPerWorkerForPeriodForm(ParticipantsPatientsTwoDatesForm):
    no_synthesis = forms.BooleanField(label=u'Exclure les synthèses', required=False, localize=True)

class PatientsSynthesisForm(TwoDatesForm):
    inscriptions = forms.BooleanField(label=u'Seulement les inscriptions', required=False, localize=True)

calebasse/statistics/views.py
# -*- coding: utf-8 -*-
import urllib

from datetime import datetime

from django.core.files import File
from django.http import HttpResponse

from calebasse.cbv import TemplateView, FormView
from calebasse.statistics import forms

from statistics import STATISTICS, Statistic


class StatisticsHomepageView(TemplateView):
    template_name = 'statistics/index.html'

    def get_context_data(self, **kwargs):
        context = super(StatisticsHomepageView, self).get_context_data(**kwargs)
        statistics = dict()
        for name, statistic in STATISTICS.iteritems():
            if not statistic.get('services') or \
                    self.service.name in statistic.get('services'):
                statistics.setdefault(statistic['category'], []).append((name,
                    statistic))
        context['statistics'] = statistics
        return context


class StatisticsDetailView(TemplateView):
    template_name = 'statistics/detail.html'

    def get_context_data(self, **kwargs):
        context = super(StatisticsDetailView, self).get_context_data(**kwargs)
        name = kwargs.get('name')
        inputs = dict()
        inputs['service'] = self.service
        inputs['start_date'] = self.request.GET.get('start_date')
        inputs['end_date'] = self.request.GET.get('end_date')
        inputs['participants'] = self.request.GET.get('participants')
        inputs['patients'] = self.request.GET.get('patients')
        inputs['inscriptions'] = self.request.GET.get('inscriptions')
        inputs['no_synthesis'] = self.request.GET.get('no_synthesis')
        statistic = Statistic(name, inputs)
        context['dn'] = statistic.display_name
        context['data_tables_set'] = statistic.get_data()
        return context


class StatisticsFormView(FormView):
    template_name = 'statistics/form.html'

    def dispatch(self, request, **kwargs):
        self.name = kwargs.get('name')
        return super(StatisticsFormView, self).dispatch(request, **kwargs)

    def get_form_class(self):
        if self.name == 'annual_activity':
            return forms.AnnualActivityForm
        elif self.name == 'patients_synthesis':
            return forms.PatientsSynthesisForm
        elif self.name == 'patients_details':
            return forms.PatientsTwoDatesForm
        elif self.name in ('active_patients_by_state_only',
                'patients_protection', 'patients_contact'):
            return forms.OneDateForm
        elif self.name == 'patients_per_worker_for_period':
            return forms.PatientsPerWorkerForPeriodForm
        elif self.name in ('active_patients_with_act', 'closed_files',
                'patients_synthesis', 'acts_synthesis',
                'acts_synthesis_cmpp', 'mises', 'deficiencies'):
            return forms.TwoDatesForm
        else:
            return forms.ParticipantsPatientsTwoDatesForm

    def form_valid(self, form):
        if 'display_or_export' in form.data:
            inputs = dict()
            inputs['service'] = self.service
            inputs['start_date'] = form.data.get('start_date')
            inputs['end_date'] = form.data.get('end_date')
            inputs['participants'] = form.data.get('participants')
            inputs['patients'] = form.data.get('patients')
            inputs['inscriptions'] = form.data.get('inscriptions')
            inputs['no_synthesis'] = 'no_synthesis' in form.data
            statistic = Statistic(self.name, inputs)
            path = statistic.get_file()
            content = File(file(path))
            response = HttpResponse(content, 'text/csv')
            response['Content-Length'] = content.size
            dest_filename = "%s--%s.csv" \
                % (datetime.now().strftime('%Y-%m-%d--%H:%M:%S'),
                statistic.display_name)
            response['Content-Disposition'] = \
                'attachment; filename="%s"' % dest_filename
            return response
        return super(StatisticsFormView, self).form_valid(form)

    def get_success_url(self):
        qs = urllib.urlencode(self.request.POST)
        target = '../../detail/%s?%s' % (self.kwargs.get('name'), qs)
        return target

calebasse/statistics/templates/statistics/base.html
{% extends "calebasse/base.html" %}

{% block extrascripts %}
<script src="{{ STATIC_URL }}js/calebasse.statistics.js"></script>
{% endblock %}

{% block title %}{{ block.super }} - Statistiques {% endblock %}

calebasse/statistics/templates/statistics/detail.html
{% extends "ressources/base.html" %}
{% load statistics_filters %}

{% block header %}
  {{ block.super }}
  <span>Statistiques - {{ service_name }}</span>
{% endblock %}

{% block appbar %}
  <h2>Statistique {{ dn }}</h2>
  <a href="../..">Retourner aux statistiques</a>
{% endblock %}

{% block content %}
    {% if data_tables_set %}
    {% for data_tables in data_tables_set %}
    <div class="statistic">
    {% for data in data_tables %}
    <table class="basic">
      <thead>
          <tr>
          {% for col in data.0 %}
          <th>{{ col }}</th>
          {% endfor %}
          </tr>
      </thead>
      <tbody>
        {% for values in data.1 %}
        <tr>
            {% for value in values %}
                {% if value|is_list %}
                <td class="width-limited">
                    <ul>
                        {% for val in value %}
                        <li>{{ val }}</li>
                        {% endfor %}
                    </ul>
                </td>
                {% elif value|is_dict %}
                <td class="width-limited {{ value.style }}">{{ value.data }}</td>
                {% else %}
                <td class="width-limited">{{ value }}</td>
                {% endif %}
            {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
    </table><br/>
    {% endfor %}
    </div><br/><br/>
    {% endfor %}
    {% endif %}
{% endblock %}

calebasse/statistics/templates/statistics/form.html
{% load widget_tweaks %}

<form action="{{ request.get_full_path }}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <script type="text/javascript">
    $('#id_start_date').datepicker({showOn: 'button'});
    $('#id_end_date').datepicker({showOn: 'button'});
    </script>
 </form>

calebasse/statistics/templates/statistics/index.html
{% extends "statistics/base.html" %}
{% load url from future %}

{% block header %}
  {{ block.super }}
  <span>Statistiques - {{ service_name }}</span>
{% endblock %}

{% block appbar %}
  <h2>Statistiques</h2>
  <a href="/">Retourner à l'accueil</a>
{% endblock %}

{% block content %}
    <ul>
     {% for category, stats in statistics.iteritems %}
         <h3>{{ category }}</h3>
         {% for n, statistic in stats %}
         <div class="statistic">
         {% if statistic.comment %}<p>{{ statistic.comment }}</p>{% endif %}
         <button id="{{ n }}" class="stats">{{ statistic.display_name }}</button>
         </div>
         {% endfor %}
     {% endfor %}
    </ul>
{% endblock %}

{% block dialogs %}
<div id="ajax-dlg" style="display: none;"></div>
{% endblock %}