calebasse/agenda/urls.py
from django.conf.urls import url, patterns, include

from calebasse.cbv import TemplateView
from django.views.decorators.csrf import csrf_exempt

from calebasse.decorators import validator_only

from views import (redirect_today, AgendaHomepageView, NewAppointmentView,
        NewEventView, AgendaServiceActivityView, UpdateAppointmentView,
        UpdateEventView, AgendaServiceActValidationView, AutomatedValidationView,
        UnlockAllView, AgendasTherapeutesView, JoursNonVerrouillesView,
        AjaxWorkerTabView, AjaxRessourceTabView, AjaxDisponibilityColumnView,
        DeleteOccurrenceView, DeleteEventView, UpdatePeriodicEventView,
        UpdatePeriodicAppointmentView, PeriodicEventsView)

agenda_patterns = patterns('',
            url(r'^$',
                AgendaHomepageView.as_view(
                    template_name='agenda/index.html'),
                name='agenda'),
            url(r'^nouveau-rdv/$',
                NewAppointmentView.as_view(),
                name='nouveau-rdv'),
            url(r'^update-rdv/(?P<pk>\d+)$',
                UpdateAppointmentView.as_view(),
                name='update-rdv'),
            url(r'^update-periodic-rdv/(?P<pk>\d+)$',
                UpdatePeriodicAppointmentView.as_view(),
                name='update-periodic-rdv'),
            url(r'^new-event/$',
                NewEventView.as_view(),
                name='new-event'),
            url(r'^update-event/(?P<pk>\d+)$',
                UpdateEventView.as_view(),
                name='update-event'),
            url(r'^update-periodic-event/(?P<pk>\d+)$',
                UpdatePeriodicEventView.as_view(),
                name='update-periodic-event'),
            url(r'^delete-occurrence/(?P<pk>\d+)$',
                csrf_exempt(DeleteOccurrenceView.as_view()),
                name='delete-occurrence'),
            url(r'^delete-event/(?P<pk>\d+)$',
                csrf_exempt(DeleteEventView.as_view()),
                name='delete-event'),
            url(r'^activite-du-service/$',
                AgendaServiceActivityView.as_view(
                    template_name='agenda/service-activity.html'),
                name='activite-du-service'),
            url(r'^validation-des-actes/$',
                validator_only(AgendaServiceActValidationView.as_view(
                    template_name='agenda/act-validation.html')),
                name='validation-des-actes'),
            url(r'^validation-des-actes/validation-all/$',
                validator_only(AutomatedValidationView.as_view()),
                name='validation-all'),
            url(r'^validation-des-actes/unlock-all/$',
                validator_only(UnlockAllView.as_view()),
                name='unlock-all'),
            url(r'^agendas-therapeutes/$',
                AgendasTherapeutesView.as_view(
                    template_name='agenda/agendas-therapeutes.html'),
                name='agendas-therapeutes'),
            url(r'^jours-non-verrouilles/$',
                validator_only(JoursNonVerrouillesView.as_view(
                    template_name='agenda/days-not-locked.html')),
                name='days-not-locked'),
            url(r'^ajax-worker-tab/(?P<worker_id>\d+)$',
                AjaxWorkerTabView.as_view(),
                name='ajax-worker-tab'),
            url(r'^ajax-ressource-tab/(?P<ressource_id>\d+)$',
                AjaxRessourceTabView.as_view(),
                name='ajax-ressource-tab'),
            url(r'^disponibility/(?P<ressource_type>\w+)-(?P<ressource_id>\d+)$',
                AjaxDisponibilityColumnView.as_view(),
                name='ajax-disponibility-column'),
            url(r'^rendez-vous-periodiques/$',
                PeriodicEventsView.as_view(),
                name='periodic-events'),
            url(r'^rendez-vous-periodiques/(?P<worker_id>\d+)/$',
                PeriodicEventsView.as_view(),
                name='periodic-events-for-worker'),
            )

urlpatterns = patterns('',
        url(r'^$', redirect_today),
        url(r'^(?P<date>[^/]*)/', include(agenda_patterns)))

calebasse/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required

from urls_utils import decorated_includes

from calebasse.api import (act_ressource, event_resource,
        eventwithact_resource, patientrecord_resource,
        patientaddress_ressource)
from tastypie.api import Api

admin.autodiscover()

v1_api = Api(api_name="v1")
v1_api.register(act_ressource)
v1_api.register(event_resource)
v1_api.register(eventwithact_resource)
v1_api.register(patientaddress_ressource)
v1_api.register(patientrecord_resource)

service_patterns = patterns('',
    url(r'^$', 'calebasse.views.homepage', name='homepage'),
    url(r'^agenda/', include('calebasse.agenda.urls')),
    url(r'^dossiers/', include('calebasse.dossiers.urls')),
    url(r'^actes/', include('calebasse.actes.urls')),
    url(r'^facturation/', include('calebasse.facturation.urls')),
    url(r'^personnes/', include('calebasse.personnes.urls')),
    url(r'^ressources/', include('calebasse.ressources.urls')),
    url(r'^statistics/', include('calebasse.statistics.urls')),
    url(r'^select2/', include('django_select2.urls')),
)

urlpatterns = patterns('',
    # Examples:
    # url(r'^calebasse/', include('aps42.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    (r'^$', 'calebasse.views.redirect_to_homepage'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout_then_login'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^api/',
        decorated_includes(login_required, include(v1_api.urls))),
    url(r'^(?P<service>[a-z-]+)/', decorated_includes(login_required,
        include(service_patterns))),
    url(r'^lookups/', include('ajax_select.urls')),
)

from django.conf import settings
if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

calebasse/agenda/models.py
# -*- coding: utf-8 -*-

from datetime import datetime, date, timedelta
from copy import copy

from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User
from django.db import models
from django import forms

from calebasse.agenda import managers
from calebasse.utils import weeks_since_epoch, weekday_ranks
from calebasse.personnes.models import Holiday

from ..middleware.request import get_request

from interval import Interval

__all__ = (
    'EventType',
    'Event',
    'EventWithAct',
)

class EventType(models.Model):
    '''
    Simple ``Event`` classifcation.
    '''
    class Meta:
        verbose_name = u'Type d\'événement'
        verbose_name_plural = u'Types d\'événement'

    def __unicode__(self):
        return self.label

    label = models.CharField(_('label'), max_length=50)
    rank = models.IntegerField(_('Sorting Rank'), null=True, blank=True, default=0)

class Event(models.Model):
    '''
    Container model for general agenda events
    '''
    objects = managers.EventManager()

    title = models.CharField(_('Title'), max_length=60, blank=True, default="")
    description = models.TextField(_('Description'), max_length=100, blank=True, null=True)
    event_type = models.ForeignKey(EventType, verbose_name=u"Type d'événement")
    creator = models.ForeignKey(User, verbose_name=_(u'Créateur'), blank=True, null=True)
    create_date = models.DateTimeField(_(u'Date de création'), auto_now_add=True)

    services = models.ManyToManyField('ressources.Service',
            null=True, blank=True, default=None)
    participants = models.ManyToManyField('personnes.People',
            null=True, blank=True, default=None)
    ressource = models.ForeignKey('ressources.Ressource', blank=True, null=True,
                                  verbose_name=u'Ressource')

    start_datetime = models.DateTimeField(_('Début'), db_index=True)
    end_datetime = models.DateTimeField(_('Fin'), blank=True, null=True)
    old_ev_id = models.CharField(max_length=8, blank=True, null=True)
    old_rr_id = models.CharField(max_length=8, blank=True, null=True)
    # only used when there is no rr id
    old_rs_id = models.CharField(max_length=8, blank=True, null=True)
    # exception to is mutually exclusive with recurrence_periodicity
    # an exception cannot be periodic
    exception_to = models.ForeignKey('self', related_name='exceptions',
            blank=True, null=True,
            verbose_name=u'Exception à')
    exception_date = models.DateField(blank=True, null=True,
            verbose_name=u'Reporté du', db_index=True)
    # canceled can only be used with exception to
    canceled = models.BooleanField(_('Annulé'), db_index=True)

    PERIODS = (
            (1, u'Toutes les semaines'),
            (2, u'Une semaine sur deux'),
            (3, u'Une semaine sur trois'),
            (4, 'Une semaine sur quatre'),
            (5, 'Une semaine sur cinq')
    )
    OFFSET = range(0, 4)
    PERIODICITIES = (
            (1, u'Toutes les semaines'),
            (2, u'Une semaine sur deux'),
            (3, u'Une semaine sur trois'),
            (4, u'Une semaine sur quatre'),
            (5, u'Une semaine sur cinq'),
            (6, u'La première semaine du mois'),
            (7, u'La deuxième semaine du mois'),
            (8, u'La troisième semaine du mois'),
            (9, u'La quatrième semaine du mois'),
            (13, u'La cinquième semaine du mois'),
            (10, u'La dernière semaine du mois'),
            (11, u'Les semaines paires'),
            (12, u'Les semaines impaires')
    )
    WEEK_RANKS = (
            (0, u'La première semaine du mois'),
            (1, u'La deuxième semaine du mois'),
            (2, u'La troisième semaine du mois'),
            (3, u'La quatrième semaine du mois'),
            (4, u'La cinquième semaine du mois'),
            (-1, u'La dernière semaine du mois'),
#            (-2, u'L\'avant dernière semaine du mois'),
#            (-3, u'L\'antépénultième semaine du mois'),
#            (-4, u'L\'anté-antépénultième semaine du mois'),
#            (-5, u'L\'anté-anté-antépénultième semaine du mois')

    )
    PARITIES = (
            (0, u'Les semaines paires'),
            (1, u'Les semaines impaires')
    )
    recurrence_periodicity = models.PositiveIntegerField(
            choices=PERIODICITIES,
            verbose_name=u"Périodicité",
            default=None,
            blank=True,
            null=True,
            db_index=True)
    recurrence_week_day = models.PositiveIntegerField(default=0, db_index=True)
    recurrence_week_offset = models.PositiveIntegerField(
            choices=zip(OFFSET, OFFSET),
            verbose_name=u"Décalage en semaines par rapport au 1/1/1970 pour le calcul de période",
            default=0,
            db_index=True)
    recurrence_week_period = models.PositiveIntegerField(
            choices=PERIODS,
            verbose_name=u"Période en semaines",
            default=None,
            blank=True,
            null=True,
            db_index=True)
    recurrence_week_rank = models.IntegerField(
            verbose_name=u"Rang de la semaine dans le mois",
            choices=WEEK_RANKS,
            blank=True, null=True, db_index=True)
    recurrence_week_parity = models.PositiveIntegerField(
            choices=PARITIES,
            verbose_name=u"Parité des semaines",
            blank=True,
            null=True,
            db_index=True)
    recurrence_end_date = models.DateField(
            verbose_name=_(u'Fin de la récurrence'),
            blank=True, null=True,
            db_index=True)

    PERIOD_LIST_TO_FIELDS = [(1, None, None),
        (2, None, None),
        (3, None, None),
        (4, None, None),
        (5, None, None),
        (None, 0, None),
        (None, 1, None),
        (None, 2, None),
        (None, 3, None),
        (None, -1, None),
        (None, None, 0),
        (None, None, 1),
        (None, 4, None),
    ]

    class Meta:
        verbose_name = u'Evénement'
        verbose_name_plural = u'Evénements'
        ordering = ('start_datetime', 'end_datetime', 'title')
        unique_together = (('exception_to', 'exception_date'),)

    def __init__(self, *args, **kwargs):
        if kwargs.get('start_datetime') and not kwargs.has_key('recurrence_end_date'):
            kwargs['recurrence_end_date'] = kwargs.get('start_datetime').date()
        super(Event, self).__init__(*args, **kwargs)

    def clean(self):
        '''Initialize recurrence fields if they are not.'''
        self.sanitize()
        if self.recurrence_periodicity:
            if self.recurrence_end_date and self.start_datetime and self.recurrence_end_date < self.start_datetime.date():
                raise forms.ValidationError(u'La date de fin de périodicité doit être postérieure à la date de début.')
        if self.recurrence_week_parity is not None:
            if self.start_datetime:
                week = self.start_datetime.date().isocalendar()[1]
                start_week_parity = week % 2
                if start_week_parity != self.recurrence_week_parity:
                    raise forms.ValidationError(u'La date de départ de la périodicité est en semaine {week}.'.format(week=week))
        if self.recurrence_week_rank is not None and self.start_datetime:
            start_week_ranks = weekday_ranks(self.start_datetime.date())
            if self.recurrence_week_rank not in start_week_ranks:
                raise forms.ValidationError('La date de début de périodicité doit faire partie de la bonne semaine dans le mois.')

    def sanitize(self):
        if self.recurrence_periodicity:
            l = self.PERIOD_LIST_TO_FIELDS[self.recurrence_periodicity-1]
        else:
            l = None, None, None
        self.recurrence_week_period = l[0]
        self.recurrence_week_rank = l[1]
        self.recurrence_week_parity = l[2]
        if self.start_datetime:
            if self.recurrence_periodicity:
                self.recurrence_week_day = self.start_datetime.weekday()
            if self.recurrence_week_period is not None:
                self.recurrence_week_offset = weeks_since_epoch(self.start_datetime) % self.recurrence_week_period

    def timedelta(self):
        '''Distance between start and end of the event'''
        return self.end_datetime - self.start_datetime

    @property
    def time(self):
        return self.start_datetime.time()

    @property
    def date(self):
        return self.start_datetime.date()

    @property
    def duration(self):
        if self.timedelta():
            return self.timedelta().seconds / 60
        return 0

    def match_date(self, date):
        if self.is_recurring():
            # consider exceptions
            exception = self.get_exceptions_dict().get(date)
            if exception is not None:
                return exception if exception.match_date(date) else None
            if self.canceled:
                return None
            if date.weekday() != self.recurrence_week_day:
                return None
            if self.start_datetime.date() > date:
                return None
            if self.recurrence_end_date and self.recurrence_end_date < date:
                return None
            if self.recurrence_week_period is not None:
                if weeks_since_epoch(date) % self.recurrence_week_period != self.recurrence_week_offset:
                    return None
            elif self.recurrence_week_parity is not None:
                if date.isocalendar()[1] % 2 != self.recurrence_week_parity:
                    return None
            elif self.recurrence_week_rank is not None:
                if self.recurrence_week_rank not in weekday_ranks(date):
                    return None
            else:
                raise NotImplemented
            return self
        else:
            return self if date == self.start_datetime.date() else None

calebasse/agenda/templates/agenda/appointment.html
{% load widget_tweaks %}
{% load url from future %}
{{ form.non_field_errors }}
{{ form.start_datetime }}
{{ form.start_datetime.errors }}
   {% if object.is_recurring and object.one_act_not_new %}<p><em>Le rendez-vous périodique a un acte qui est pointé ce qui empêche de le modifier à l'exception de la description, de la ressource et de la date de fin.</em></p>{% endif %}
   {% if object.is_recurring and object.one_act_not_new %}<p><em>Le rendez-vous périodique a un acte qui est pointé ce qui empêche de le supprimer.</em></p>{% endif %}
   <table id="new-appointment-table">
       <tr>
           <td {% if form.time.field.required %}class="required"{% endif %}>
            <p>
           {{ form.time.label_tag }}
           {% if object.is_recurring and object.one_act_not_new %}
           {{ object.time }}
           {{ form.time.as_hidden }}
           {% else %}
           {{ form.time }}
           {% endif %}
           {{ form.time.errors }}
           </p>
           </td>
           <td {% if form.duration.field.required %}class="required"{% endif %}>
           <p>
           {{ form.duration.label_tag }}
           {% if object.is_recurring and object.one_act_not_new %}
           {{ object.duration }}
           {{ form.duration.as_hidden }}
           {% else %}
           {{ form.duration }}
           {% endif %}
           {{ form.duration.errors }}
           </p>
           </td>
           <td {% if form.date.field.required %}class="required"{% endif %}>
           <p class="datepicker">
           {{ form.date.label_tag }}
           {% if object.is_recurring and object.one_act_not_new %}
           {{ object.date }}
           {{ form.date.as_hidden }}
           {% else %}
           {{ form.date|add_class:"datepicker-date" }}
           {% endif %}
           {{ form.date.errors }}
           </p>
           </td>
       </tr>
       <tr>
           <td>
           <p>
           {{ form.ressource.label_tag }}
           {{ form.ressource }}
           {{ form.ressource.errors }}
           </p>
           </td>
       </tr>
       <tr>
           <td {% if form.participants.field.required %}class="required"{% endif %}>
           <h4>{{ form.participants.label_tag }}</h4>
           <div id="intervenants">
           {% if object.is_recurring and object.one_act_not_new %}
           <ul>{% for p in object.participants.all %}<li>{{ p }}</li>{% endfor %}</ul>
           <input id="id_participants" name="participants" value="|{% for p in object.participants.all %}{{ p.id }}|{% endfor %}" type="hidden"/>
           {% else %}
           {{ form.participants }}
           {% endif %}
           {{ form.participants.errors }}
           </div>
           </td>
           <td {% if form.patient.field.required %}class="required"{% endif %}>
           <h4>{{ form.patient.label_tag }}</h4>
           <div id="patient">
           {% if object.is_recurring or object.exception_to or object.act.already_billed %}
           {{ object.patient }}
           {{ form.patient.as_hidden }}
           {% else %}
           {{ form.patient }}
           {{ form.patient.errors }}
           {% endif %}
           </div>
           </td>
           <td {% if form.act_type.field.required %}class="required"{% endif %}>
           <h4>{{ form.act_type.label_tag }}</h4>
           {% if object.is_recurring and object.one_act_not_new %}
           {{ object.act_type }}
           {{ form.act_type.as_hidden }}
           {% else %}
           {{ form.act_type }}
           {% endif %}
           {{ form.act_type.errors }}
           </td>
       </tr>
      <tr>
        <td colspan="3">
          <div id="description">
            {{ form.description.label_tag }}
            {{ form.description }}
            {{ form.description.errors }}
          </div>
        </td>
      </tr>
</table>

{% if object.exception_to %}
  <hr/>
  {% if object.id != object.exception_to.id %}
  <p><em><strong>Attention: cette occurrence est une exception au rendez-vous périodique</strong>; si vous modifiez l'heure, la durée, le commentaire, la ressource, les participants ou le type d'acte du rendez-vous périodique, les exceptions ne sont pas modifiées.</em></p>
  {% endif %}

  <p>Occurence du {{object.exception_date}} d'un rendez-vous périodique
    {% if object.exception_to.canceled %}<em>supprimé</em> et initialement prévu{% endif %}
    {{ object.exception_to.recurrence_description|lower }}</p>

  {% if not object.exception_to.canceled %}
  <p><button type="button" data-delete-url="{% url 'delete-event' service=service date=date pk=object.exception_to.pk %}" data-id="{{ object.exception_to.id }}" data-one_act_not_new="{{ object.exception_to.one_act_not_new }}"  class="update-periodic-rdv">Éditer le rendez-vous périodique</button></p>
  {% endif %}

{% endif %}

calebasse/agenda/templates/agenda/automated-validation.html
<div id="valider-dlg">
   <h3>Bilan</h3>
   <ul>
    <li>Actes total : {{nb_acts_total}}</li>
    {% if nb_acts_validated %}<li>Actes validés : {{nb_acts_validated}}</li>{% else %}<li>Aucun acte validé</li>{% endif %}
    {% if nb_acts_not_validated %}
        <li>Actes non validés : {{nb_acts_not_validated}}</li>
        <ul>
        {% if nb_acts_double %}<li>Actes en double : {{nb_acts_double}}</li>{% endif %}
        {% if nb_acts_abs_non_exc %}<li>Abscences non excusées : {{nb_acts_abs_non_exc}}</li>{% endif %}
        {% if nb_acts_abs_exc %}<li>Abscences excusées : {{nb_acts_abs_exc}}</li>{% endif %}
        {% if nb_acts_abs_inter %}<li>Abscences intervenants : {{nb_acts_abs_exc}}</li>{% endif %}
        {% if nb_acts_annul_nous %}<li>Annulés par nous : {{nb_acts_annul_nous}}</li>{% endif %}
        {% if nb_acts_annul_famille %}<li>Annulés par la famille : {{nb_acts_annul_famille}}</li>{% endif %}
        {% if nb_acts_abs_ess_pps %}<li>Abscences ESS PPS : {{nb_acts_abs_ess_pps}}</li>{% endif %}
        {% if nb_acts_enf_hosp %}<li>Absences pour enfant hospitalisé : {{nb_acts_enf_hosp}}</li>{% endif %}
        {% if nb_acts_losts %}<li>Actes perdus : {{nb_acts_losts}}</li>{% endif %}
        </ul>
    {% endif %}
  </ul>
</div>

calebasse/agenda/templates/agenda/base.html
{% extends "calebasse/base.html" %}
{% load url from future %}

{% block extrascripts %}
{{ block.super }}
<script src="{{ STATIC_URL }}js/json2.js"></script>
<script src="{{ STATIC_URL }}js/calebasse.agenda.js"></script>
<script src="{{ STATIC_URL }}js/calebasse.datesel.js"></script>
{% endblock %}
{% block extrastyles %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/agenda.css" />
{% endblock extrastyles %}

{% block title %}{{ block.super }} - Agenda {% endblock %}

{% block header %}
  {{ block.super }}
  <span>Agenda - {{ service_name }}</span>
{% endblock %}

{% block content %}
<div class="content">
   {% include "calebasse/datesel.html" %}
   {% block agenda-content %}
   {% endblock %}
</div>
{% endblock %}

calebasse/agenda/templates/agenda/days-not-locked.html
{% extends "agenda/base.html" %}
{% load url from future %}

{% block body-class %}{{ block.super }} no-left-column{% endblock %}

{% block appbar %}
<h2>Jours non verrouillés</h2>
    <a href="..">Retourner à l'agenda</a>
{% endblock %}

{% block content %}
{% if days_not_locked %}
<ul>
{% for day in days_not_locked %}
    <li><a href="../../{{ day.year }}-{{ day.month }}-{{ day.day }}/validation-des-actes">{{ day.day }}/{{ day.month }}/{{ day.year }}</a></li>
{% endfor %}
</ul>
{% endif %}
{% endblock %}

calebasse/agenda/templates/agenda/periodic-events.html
{% extends "agenda/base.html" %}
{% load widget_tweaks %}
{% load url from future %}
{% load apptags %}

{% block extrascripts %}
{{ block.super }}
<script type="text/javascript" src="{{ STATIC_URL }}/js/calebasse.reset-button.js">
</script>
<script>
  function add_datepickers(that) {
    $('input#id_date', that).datepicker({dateFormat: 'd/m/yy', showOn: 'button' });
    $('input#id_recurrence_end_date', that).datepicker({dateFormat: 'd/m/yy', showOn: 'button' });
  }
  $(function () {
    var update_periodic_event_url = "{% url 'update-periodic-event' service=service date=date pk=0 %}";
    var update_periodic_appointment_url = "{% url 'update-periodic-rdv' service=service date=date pk=0 %}";

    $('button.edit-periodic-appointment').on('click', function () {
      var id = $(this).data('event-id');
      var title = $(this).data('title');
      generic_ajaxform_dialog(update_periodic_appointment_url + id,
        title, '#event-dlg', 950, 'Modifier',
        "{% url 'periodic-events' service=service date=date %}", add_datepickers);
    });
    $('button.edit-periodic-event').on('click', function () {
      var id = $(this).data('event-id');
      var title = $(this).data('title');
      generic_ajaxform_dialog(update_periodic_event_url + id,
        title, '#event-dlg', 950, 'Modifier',
        "{% url 'periodic-events' service=service date=date %}", add_datepickers);
    });
  });
</script>
{% endblock %}

{% block appbar %}
<h2>Rendez-vous périodiques{% if worker %} de {{ worker }}{% endif %}</h2>
<a href="{% url 'agenda' service=service date=date %}">Retourner à l'agenda</a>
{% endblock %}
{% block content %}
<div id="sidebar">
  <form id="periodic-events-search-form">
    <div class="field">
      <label for="start_date">Rendez-vous périodiques possédant une occurence dans les trois mois qui suivent le&nbsp;:</label>
      {{ search_form.start_date|add_class:"datepicker-date" }}
    </div>
    <p>OU</p>
    <div class="field">
    <label for="end_date">Rendez-vous périodiques possèdant une occurence avant le&nbsp;:</label>
    {{ search_form.end_date|add_class:"datepicker-date" }}
    </div>
    <div class="field">
      {{ search_form.event_type }}
      <label for="no_end_date">{{ search_form.no_end_date }} Sans date de fin</label>
    </div>
    <div class="field">
      <label for="patient">avec le patient:</label>
      {{ search_form.patient }}
    </div>
    <div class="field">
      <label for="patient">avec le participant:</label>
      {{ search_form.worker }}
    </div>
    {% if request.GET %}
    <div class="search-reset">
    <button id="search">Rechercher</button>
    <button id="reset" class="icon-remove-sign" title="Réinitialiser"></button>
    </div>
    {% else %}
    <button id="search">Rechercher</button>
    {% endif %}
  </form>
</div>
<script>
  $('.datepicker-date').datepicker({dateFormat: 'd/m/yy', showOn: 'button'});
</script>
<div class="content">
  {% if request.GET %}
  <p>{{ object_list|length }} évènement(s) trouvé(s).</p>
  {% endif %}
  {% for event in object_list %}
  <div id="events">
    <div class="event frame" id="event-frame-{{ event.id }}">
      <h3>
        <span>{% if event.patient %}Rendez-vous patient{% else %}Évènement{% endif %}: {{ event.recurrence_description|lower }}</span>
         —
        <span class="hour">{{ event.start_datetime.time }}</span>
        {% if event.patient %} — {{ event.patient.display_name }} {% else %}{% if event.title %} — {{ event.title }} {% endif %}{% endif %}
        {% if event.patient.paper_id %} — {{ event.patient.paper_id }} {% endif %}
        {% if event.length %} — {{ event.length }} min {% endif %}
        {% if event.workers_initial %} — {{ event.workers_initial }} {% endif %}
        {% if event.ressource %} — {{ event.ressource }} {% endif %}
        <span class="right">
          {% for other_service in event.services.all %}
            {% if other_service.name != service_name %}
              <span class="box {{ other_service.slug }}" title="{{ other_service.name }}"></span>
            {% endif %}
          {% endfor %}
          {% if event.description %}
            <span title="Un commentaire existe" class="icon-comment"></span>
          {% endif %}
         {% if event.event_type_id == 1 %}
           <button title="Éditer un rendez-vous" class="edit-periodic-appointment icon-edit" data-event-id="{{ event.id }}"></button>
         {% else %}
           <button title="Éditer un événement" class="edit-periodic-event icon-edit" data-event-id="{{ event.id }}">
         {% endif %}
        </span>
      </h3>
      {% if event.act_type %}
        <p>Type: {{ event.act_type }}</p>
      {% endif %}
        <p>Avec:
          {% for participant in event.participants.all %}
            {{ participant }}{% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
    </div>
  </div>
  {% endfor %}
  {% if not request.GET %}
    <div class="big-msg-info">
      Utilisez le formulaire de recherche sur la gauche de l'écran pour afficher
      les rendez-vous périodiques correspondants.
    </div>
  {% elif not object_list %}
    <div>Pas de résultat pour votre recherche</div>
  {% endif %}
</div>
{% endblock %}

{% block dialogs %}
<div id="event-dlg" style="display: none">
</div>
{% endblock %}

calebasse/agenda/templates/agenda/update-event.html
<form action="{{ request.get_full_path}}" method="post">
  {% csrf_token %}
  {% include "agenda/event.html" %}
</form>

calebasse/agenda/templates/agenda/update-rdv.html
<form action="{{ request.get_full_path}}" method="post">
  {% csrf_token %}
  {% include "agenda/appointment.html" %}
</form>